== Hosts

=== CSV-Import

Für den Import von Host-Daten legt man eine CSV-Datei an mit Separator `;` und
den Attributnamen in der Kopfzeile. Die Attribute `ip` und `lastseen` sind
zwingend erforderlich. `ip` ist derzeit das einzige Identifikationsmerkmal für
den Host, über `lastseen` (sprich: zuletzt gesehen, zuletzt aktiv) erfolgt die
Steuerung abhängig vom Importmodus, ob überhaupt Daten aus der Tabelle
übernommen werden oder nicht.

IMPORTANT: Wenn aus manuell erzeugten oder gepflegten Tabellen Daten
importiert werden sollen, muss ebenfalls `lastseen` gesetzt sein - `lastseen`
wird allerdings dabei auch aktualisiert.


.Beispiel für eine Import-Tabelle
[options="header"]
|===
| ip | lastseen | attr1 | attr2 | ... | attrN |
|192.0.2.4 | 2019-03-01  | xxx | xxx | ... | xxx |
|===

==== Attribute

.Importierbare Attribute
[options="header", cols="20,80"]
|===
|Attribut
|Beschreibung

| `ip`
| IP-Adresse des Hosts

|`name`
|

|`description`
|

|`cpe`
|

|`raw_os`
|

|`operating_system_id`
|

|`lastseen`
|

|`mac`
|

|`host_category_id`
|

|`location_id`
|

|`fqdn`
|

|`workgroup`
|

|`domain_dns`
|

|`vendor`
|

|`serial`
|

|===

.Ermittlung der für den Import verwendbaren Attribute
[source]
----
  def host_attributes <!--1-->
    Host.attribute_names.map(&:to_sym).reject do |k|
      [:id, :created_at, :updated_at, :vuln_risk, :oui_vendor].include?(k)
    end
  end
----
<1> `app/services/import_csv_hosts_service.rb:109`

.Verwendbare Attribute (Ausgabe von `host_attributes`)
[source]
----
[:name, :description, :ip, :cpe, :raw_os, :operating_system_id, :lastseen, :mac, :host_category_id, :location_id, :fqdn, :workgroup, :domain_dns, :vendor, :serial]
----
