== Hosts

=== CSV-Import

Für den Import von Host-Daten legt man eine CSV-Datei an mit Separator `;` und
den Attributnamen in der Kopfzeile. Die Attribute `ip` und `lastseen` sind
zwingend erforderlich. `ip` ist derzeit das einzige Identifikationsmerkmal für
den Host, über `lastseen` (sprich: zuletzt gesehen, zuletzt aktiv) erfolgt die
Steuerung abhängig vom Importmodus, ob überhaupt Daten aus der Tabelle
übernommen werden oder nicht.

IMPORTANT: Wenn aus manuell erzeugten oder gepflegten Tabellen Daten
importiert werden sollen, muss ebenfalls `lastseen` gesetzt sein - `lastseen`
wird allerdings dabei auch aktualisiert.


.Beispiel für eine Import-Tabelle
[options="header"]
|===
| ip | lastseen | attr1 | attr2 | ... | attrN |
|192.0.2.4 | 2019-03-01  | xxx | xxx | ... | xxx |
|===

==== Attribute

.Importierbare Attribute
[options="header", cols="20,80"]
|===
|Attribut
|Beschreibung

| `ip`
| IP-Adresse des Hosts

|`name`
| Hostname

|`description`
| Beschreibung der Aufgabe oder anderweitige Angaben

|`cpe`
| Common Plattform Enumeration; eine Angabe zum Betriebssystem z.B. aus `nmap`-Scans.

|`raw_os`
| Betriebssystemangabe. Boskop versucht die Angabe  dann einem Betriebssystem aus der Betriebssystemtabelle zuzuordnen.

|`operating_system_id`
|Name oder ID aus der Betriebssystem-Tabelle. Ein Tag ist derzeit noch nicht implementiert.

|`lastseen`
| Zuletzt gesehen am; Format: `YYYY-MM-DD`

|`mac`
| MAC-Adresse

|`host_category_id`
| ID, Name oder Tag aus der Host-Kategorie-Tabelle.

|`location_id`
|Name, Lokation_ID oder ID der Lokation aus der Lokation-Tabelle.

|`fqdn`
| Full Qualified Domain Name

|`workgroup`
| Windows-Arbeitsgruppe

|`domain_dns`
|Windows-Domäne

|`vendor`
|Hersteller (der Host-Hardware)

|`serial`
|Seriennummer (Bios-Seriennummer)

|`uuid`
|UUID (Bios- oder Motherboard)

|`product`
|Herstellerbezeichnung des Produktes, z.B. Optiplex 3030

|`warranty_sla`, `warranty_start`, `warranty_end`
|Garantiedaten zum System: SLA, Start (Datum), Ende (Datum)

|===

.Ermittlung der für den Import verwendbaren Attribute
[source]
----
  def host_attributes <!--1-->
    Host.attribute_names.map(&:to_sym).reject do |k|
      [:id, :created_at, :updated_at, :vuln_risk].include?(k)
    end
  end
----
<1> `app/services/import_csv_hosts_service.rb:109`

.Verwendbare Attribute (Ausgabe von `host_attributes`)
[source]
----
[:id, :name, :description, :cpe, :raw_os, :operating_system_id, :lastseen,
:host_catego ry_id, :location_id, :created_at, :updated_at, :fqdn, :workgroup,
:domain_dns, :vendor, :v uln_risk, :serial, :uuid, :product, :warranty_sla,
:warranty_start, :warranty_end]
----
