// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PivottableController from "./pivottable_controller"
application.register("pivottable", PivottableController)

import Ts__SelectController from "./ts/select_controller"
application.register("ts--select", Ts__SelectController)
