shared_context "host variables" do
  let!(:cat_linux) { FactoryGirl.create(:host_category, name: 'linux') }
  let!(:loc_paris) { FactoryGirl.create(:location, name: 'Paris', lid: 'PARIS') }
  # order "name asc": MYNAS01, MYPC002, MYPC003, MYPC005, vpngw
  let!(:nas)  { FactoryGirl.create(:host, 
    name: "MYNAS01",
    description: "Backup station",
    ip: '198.51.100.17',
    cpe: "cpe:/o:linux:linux_kernel:2.6",
    raw_os: "storage-misc",
    fqdn: 'nas01.my.example.net',
    domain_dns: 'my.example.net',
    workgroup: 'MY',
    lastseen: Date.today,
    mac: '00:84:ed:12:34:56',
    location: loc_paris,
  )}
  let!(:pc2)  { FactoryGirl.create(:host, 
    name: "MYPC002",
    description: "workstation",
    ip: '198.51.100.63',
    cpe: "cpe:/o:microsoft:windows_7::sp1:professional",
    raw_os: "Windows 7 Professional 7601 Service Pack 1",
    fqdn: 'mypc002.my.example.net',
    domain_dns: 'my.example.net',
    workgroup: 'MY',
    lastseen: Date.today,
    mac: '00:84:ed:00:12:02',
  )}
  let!(:pc3)  { FactoryGirl.create(:host, 
    name: "MYPC003",
    description: "workstation",
    ip: '198.51.100.66',
    cpe: "cpe:/o:microsoft:windows_7::sp1:professional",
    raw_os: "Windows 7 Professional 7601 Service Pack 1",
    fqdn: 'mypc003.my.example.net',
    domain_dns: 'my.example.net',
    workgroup: 'MY',
    lastseen: Date.today,
    mac: '00:84:ed:00:12:03',
  )}
  let!(:vpngw)  { FactoryGirl.create(:host, 
    name: "vpngw",
    description: "VPN gateway",
    ip: '203.0.113.1',
    cpe: "cpe:/o:linux:linux_kernel:4.4",
    raw_os: "Linux 4.4",
    fqdn: 'vpngw.external.net',
    domain_dns: 'external.net',
    workgroup: '',
    lastseen: 1.month.before(Date.today),
    mac: '12:34:56:99:99:98',
    host_category: cat_linux,
  )}
  let!(:pc5)  { FactoryGirl.create(:host, 
    name: "MYPC005",
    description: "very old workstation",
    ip: '198.51.100.70',
    cpe: "cpe:/o:microsoft:windows_xp::-",
    raw_os: "Windows 5.1",
    fqdn: 'mypc005.my.example.net',
    domain_dns: 'my.example.net',
    workgroup: 'MY',
    lastseen: 1.year.before(Date.today),
    mac: '00:84:ed:00:12:05',
  )}
end

