require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FrameworkContractsController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # FrameworkContract. As you add validations to FrameworkContract, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:framework_contract)
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FrameworkContractsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all framework_contracts as @framework_contracts" do
      framework_contract = FrameworkContract.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:framework_contracts)).to eq([framework_contract])
    end
  end

  describe "GET #show" do
    it "assigns the requested framework_contract as @framework_contract" do
      framework_contract = FrameworkContract.create! valid_attributes
      get :show, {:id => framework_contract.to_param}, valid_session
      expect(assigns(:framework_contract)).to eq(framework_contract)
    end
  end

  describe "GET #new" do
    it "assigns a new framework_contract as @framework_contract" do
      get :new, {}, valid_session
      expect(assigns(:framework_contract)).to be_a_new(FrameworkContract)
    end
  end

  describe "GET #edit" do
    it "assigns the requested framework_contract as @framework_contract" do
      framework_contract = FrameworkContract.create! valid_attributes
      get :edit, {:id => framework_contract.to_param}, valid_session
      expect(assigns(:framework_contract)).to eq(framework_contract)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FrameworkContract" do
        expect {
          post :create, {:framework_contract => valid_attributes}, valid_session
        }.to change(FrameworkContract, :count).by(1)
      end

      it "assigns a newly created framework_contract as @framework_contract" do
        post :create, {:framework_contract => valid_attributes}, valid_session
        expect(assigns(:framework_contract)).to be_a(FrameworkContract)
        expect(assigns(:framework_contract)).to be_persisted
      end

      it "redirects to the created framework_contract" do
        post :create, {:framework_contract => valid_attributes}, valid_session
        expect(response).to redirect_to(FrameworkContract.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved framework_contract as @framework_contract" do
        post :create, {:framework_contract => invalid_attributes}, valid_session
        expect(assigns(:framework_contract)).to be_a_new(FrameworkContract)
      end

      it "re-renders the 'new' template" do
        post :create, {:framework_contract => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { description: "small typo fixes" }
      }

      it "updates the requested framework_contract" do
        framework_contract = FrameworkContract.create! valid_attributes
        put :update, {:id => framework_contract.to_param, :framework_contract => new_attributes}, valid_session
        framework_contract.reload
        expect(framework_contract.description).to eq("small typo fixes")
      end

      it "assigns the requested framework_contract as @framework_contract" do
        framework_contract = FrameworkContract.create! valid_attributes
        put :update, {:id => framework_contract.to_param, :framework_contract => valid_attributes}, valid_session
        expect(assigns(:framework_contract)).to eq(framework_contract)
      end

      it "redirects to the framework_contract" do
        framework_contract = FrameworkContract.create! valid_attributes
        put :update, {:id => framework_contract.to_param, :framework_contract => valid_attributes}, valid_session
        expect(response).to redirect_to(framework_contract)
      end
    end

    context "with invalid params" do
      it "assigns the framework_contract as @framework_contract" do
        framework_contract = FrameworkContract.create! valid_attributes
        put :update, {:id => framework_contract.to_param, :framework_contract => invalid_attributes}, valid_session
        expect(assigns(:framework_contract)).to eq(framework_contract)
      end

      it "re-renders the 'edit' template" do
        framework_contract = FrameworkContract.create! valid_attributes
        put :update, {:id => framework_contract.to_param, :framework_contract => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested framework_contract" do
      framework_contract = FrameworkContract.create! valid_attributes
      pending "line not yet implemented"
      expect {
        delete :destroy, {:id => framework_contract.to_param}, valid_session
      }.to change(FrameworkContract, :count).by(-1)
    end

    it "redirects to the framework_contracts list" do
      framework_contract = FrameworkContract.create! valid_attributes
      pending "line not yet implemented"
      delete :destroy, {:id => framework_contract.to_param}, valid_session
      expect(response).to redirect_to(framework_contracts_url)
    end
  end

end
