require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LineStatesController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # LineState. As you add validations to LineState, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:line_state)
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LineStatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all line_states as @line_states" do
      line_state = LineState.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:line_states)).to eq([line_state])
    end
  end

  describe "GET #show" do
    it "assigns the requested line_state as @line_state" do
      line_state = LineState.create! valid_attributes
      get :show, {:id => line_state.to_param}, valid_session
      expect(assigns(:line_state)).to eq(line_state)
    end
  end

  describe "GET #new" do
    it "assigns a new line_state as @line_state" do
      get :new, {}, valid_session
      expect(assigns(:line_state)).to be_a_new(LineState)
    end
  end

  describe "GET #edit" do
    it "assigns the requested line_state as @line_state" do
      line_state = LineState.create! valid_attributes
      get :edit, {:id => line_state.to_param}, valid_session
      expect(assigns(:line_state)).to eq(line_state)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LineState" do
        expect {
          post :create, {:line_state => valid_attributes}, valid_session
        }.to change(LineState, :count).by(1)
      end

      it "assigns a newly created line_state as @line_state" do
        post :create, {:line_state => valid_attributes}, valid_session
        expect(assigns(:line_state)).to be_a(LineState)
        expect(assigns(:line_state)).to be_persisted
      end

      it "redirects to the created line_state" do
        post :create, {:line_state => valid_attributes}, valid_session
        expect(response).to redirect_to(LineState.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved line_state as @line_state" do
        post :create, {:line_state => invalid_attributes}, valid_session
        expect(assigns(:line_state)).to be_a_new(LineState)
      end

      it "re-renders the 'new' template" do
        post :create, {:line_state => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { description: "sonstnochwas" }
      }

      it "updates the requested line_state" do
        line_state = LineState.create! valid_attributes
        put :update, {:id => line_state.to_param, :line_state => new_attributes}, valid_session
        line_state.reload
        expect(line_state.description).to eq("sonstnochwas")
      end

      it "assigns the requested line_state as @line_state" do
        line_state = LineState.create! valid_attributes
        put :update, {:id => line_state.to_param, :line_state => valid_attributes}, valid_session
        expect(assigns(:line_state)).to eq(line_state)
      end

      it "redirects to the line_state" do
        line_state = LineState.create! valid_attributes
        put :update, {:id => line_state.to_param, :line_state => valid_attributes}, valid_session
        expect(response).to redirect_to(line_state)
      end
    end

    context "with invalid params" do
      it "assigns the line_state as @line_state" do
        line_state = LineState.create! valid_attributes
        put :update, {:id => line_state.to_param, :line_state => invalid_attributes}, valid_session
        expect(assigns(:line_state)).to eq(line_state)
      end

      it "re-renders the 'edit' template" do
        line_state = LineState.create! valid_attributes
        put :update, {:id => line_state.to_param, :line_state => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested line_state" do
      line_state = LineState.create! valid_attributes
      pending "line not yet implemented"
      expect {
        delete :destroy, {:id => line_state.to_param}, valid_session
      }.to change(LineState, :count).by(-1)
    end

    it "redirects to the line_states list" do
      line_state = LineState.create! valid_attributes
      pending "line not yet implemented"
      delete :destroy, {:id => line_state.to_param}, valid_session
      expect(response).to redirect_to(line_states_url)
    end
  end

end
