require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MerkmalklassenController, :type => :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # Merkmalklasse. As you add validations to Merkmalklasse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:merkmalklasse)
  }

  let(:invalid_attributes) {
    { format: 'invalid format' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MerkmalklassenController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all merkmalklassen as @merkmalklassen" do
      merkmalklasse = Merkmalklasse.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:merkmalklassen)).to eq([merkmalklasse])
    end
  end

  describe "GET show" do
    it "assigns the requested merkmalklasse as @merkmalklasse" do
      merkmalklasse = Merkmalklasse.create! valid_attributes
      get :show, {:id => merkmalklasse.to_param}, valid_session
      expect(assigns(:merkmalklasse)).to eq(merkmalklasse)
    end
  end

  describe "GET new" do
    it "assigns a new merkmalklasse as @merkmalklasse" do
      get :new, {}, valid_session
      expect(assigns(:merkmalklasse)).to be_a_new(Merkmalklasse)
    end
  end

  describe "GET edit" do
    it "assigns the requested merkmalklasse as @merkmalklasse" do
      merkmalklasse = Merkmalklasse.create! valid_attributes
      get :edit, {:id => merkmalklasse.to_param}, valid_session
      expect(assigns(:merkmalklasse)).to eq(merkmalklasse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Merkmalklasse" do
        expect {
          post :create, {:merkmalklasse => valid_attributes}, valid_session
        }.to change(Merkmalklasse, :count).by(1)
      end

      it "assigns a newly created merkmalklasse as @merkmalklasse" do
        post :create, {:merkmalklasse => valid_attributes}, valid_session
        expect(assigns(:merkmalklasse)).to be_a(Merkmalklasse)
        expect(assigns(:merkmalklasse)).to be_persisted
      end

      it "redirects to the created merkmalklasse" do
        post :create, {:merkmalklasse => valid_attributes}, valid_session
        expect(response).to redirect_to(Merkmalklasse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved merkmalklasse as @merkmalklasse" do
        post :create, {:merkmalklasse => invalid_attributes}, valid_session
        expect(assigns(:merkmalklasse)).to be_a_new(Merkmalklasse)
      end

      it "re-renders the 'new' template" do
        post :create, {:merkmalklasse => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { format: 'number' }
      }

      it "updates the requested merkmalklasse" do
        merkmalklasse = Merkmalklasse.create! valid_attributes
        put :update, {:id => merkmalklasse.to_param, :merkmalklasse => new_attributes}, valid_session
        merkmalklasse.reload
        expect(merkmalklasse.format).to be == "number"
      end

      it "assigns the requested merkmalklasse as @merkmalklasse" do
        merkmalklasse = Merkmalklasse.create! valid_attributes
        put :update, {:id => merkmalklasse.to_param, :merkmalklasse => valid_attributes}, valid_session
        expect(assigns(:merkmalklasse)).to eq(merkmalklasse)
      end

      it "redirects to the merkmalklasse" do
        merkmalklasse = Merkmalklasse.create! valid_attributes
        put :update, {:id => merkmalklasse.to_param, :merkmalklasse => valid_attributes}, valid_session
        expect(response).to redirect_to(merkmalklasse)
      end
    end

    describe "with invalid params" do
      it "assigns the merkmalklasse as @merkmalklasse" do
        merkmalklasse = Merkmalklasse.create! valid_attributes
        put :update, {:id => merkmalklasse.to_param, :merkmalklasse => invalid_attributes}, valid_session
        expect(assigns(:merkmalklasse)).to eq(merkmalklasse)
      end

      it "re-renders the 'edit' template" do
        merkmalklasse = Merkmalklasse.create! valid_attributes
        put :update, {:id => merkmalklasse.to_param, :merkmalklasse => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested merkmalklasse" do
      merkmalklasse = Merkmalklasse.create! valid_attributes
      expect {
        delete :destroy, {:id => merkmalklasse.to_param}, valid_session
      }.to change(Merkmalklasse, :count).by(-1)
    end

    it "redirects to the merkmalklassen list" do
      merkmalklasse = Merkmalklasse.create! valid_attributes
      delete :destroy, {:id => merkmalklasse.to_param}, valid_session
      expect(response).to redirect_to(merkmalklassen_url)
    end
  end

end
