require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe NessusScansController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # NessusScan. As you add validations to NessusScan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.attributes_for(:nessus_scan)
  }

  let(:invalid_attributes) {
     { uuid: nil, name: nil, nessus_id: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NessusScansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      NessusScan.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      nessus_scan = NessusScan.create! valid_attributes
      get :show, params: {id: nessus_scan.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      nessus_scan = NessusScan.create! valid_attributes
      get :edit, params: {id: nessus_scan.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new NessusScan" do
        expect {
          post :create, params: {nessus_scan: valid_attributes}, session: valid_session
        }.to change(NessusScan, :count).by(1)
      end

      it "redirects to the created nessus_scan" do
        post :create, params: {nessus_scan: valid_attributes}, session: valid_session
        expect(response).to redirect_to(NessusScan.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {nessus_scan: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { import_state: 'done', import_mode: 'auto' }
      }

      it "updates the requested nessus_scan" do
        nessus_scan = NessusScan.create! valid_attributes
        put :update, params: {id: nessus_scan.to_param, nessus_scan: new_attributes}, session: valid_session
        nessus_scan.reload
        expect(nessus_scan.import_state).to eq("done")
        expect(nessus_scan.import_mode).to eq("auto")
      end

      it "redirects to the nessus_scan" do
        nessus_scan = NessusScan.create! valid_attributes
        put :update, params: {id: nessus_scan.to_param, nessus_scan: valid_attributes}, session: valid_session
        expect(response).to redirect_to(nessus_scan)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        nessus_scan = NessusScan.create! valid_attributes
        put :update, params: {id: nessus_scan.to_param, nessus_scan: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested nessus_scan" do
      nessus_scan = NessusScan.create! valid_attributes
      expect {
        delete :destroy, params: {id: nessus_scan.to_param}, session: valid_session
      }.to change(NessusScan, :count).by(-1)
    end

    it "redirects to the nessus_scans list" do
      nessus_scan = NessusScan.create! valid_attributes
      delete :destroy, params: {id: nessus_scan.to_param}, session: valid_session
      expect(response).to redirect_to(nessus_scans_url)
    end
  end

  describe "POST #update_list" do
    it "calls Nessus::ListScansJob.perform_now" do
      expect(Nessus::ListScansJob).to receive(:perform_now).and_return(true)
      post :update_list, params: {}, session: valid_session
      expect(response).to redirect_to(nessus_scans_url)
    end
  end

  describe "PUT #import" do
    it "calls Nessus::ListScansJob.perform_now" do
      nessus_scan = NessusScan.create! valid_attributes
      expect(Nessus::ImportScansJob).to receive(:perform_later).and_return(true)
      put :import, params: {id: nessus_scan.to_param}, session: valid_session
      expect(response).to redirect_to(nessus_scans_url)
    end
  end

end
