require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NetworksController, :type => :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # Network. As you add validations to Network, be sure to
  # adjust the attributes here as well.
  let!(:location) { FactoryGirl.create(:location) }
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:network, location_id: location.id)
  }

  let(:invalid_attributes) {
    { netzwerk: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NetworksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all networks as @networks" do
      network = Network.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:networks)).to eq([network])
    end
  end

  describe "GET show" do
    it "assigns the requested network as @network" do
      network = Network.create! valid_attributes
      get :show, {:id => network.to_param}, valid_session
      expect(assigns(:network)).to eq(network)
    end
  end

  describe "GET new" do
    it "assigns a new network as @network" do
      get :new, {}, valid_session
      expect(assigns(:network)).to be_a_new(Network)
    end
    it "assigns a netzwerk to new network @network" do
      get :new, {netzwerk: "10.20.30.0/24"}, valid_session
      expect(assigns(:network).netzwerk.to_cidr_s).to eq("10.20.30.0/24")
    end
    it "assigns a description to new network @network" do
      get :new, {description: "brabbelfasel"}, valid_session
      expect(assigns(:network).description).to eq("brabbelfasel")
    end
    it "assigns location_id to new network @network" do
      get :new, {location_id: "47110815"}, valid_session
      expect(assigns(:network).location_id).to eq(47110815)
    end
  end

  describe "GET edit" do
    it "assigns the requested network as @network" do
      network = Network.create! valid_attributes
      get :edit, {:id => network.to_param}, valid_session
      expect(assigns(:network)).to eq(network)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Network" do
        expect {
          post :create, {:network => valid_attributes}, valid_session
        }.to change(Network, :count).by(1)
      end

      it "assigns a newly created network as @network" do
        post :create, {:network => valid_attributes}, valid_session
        expect(assigns(:network)).to be_a(Network)
        expect(assigns(:network)).to be_persisted
      end

      it "redirects to the created network" do
        post :create, {:network => valid_attributes}, valid_session
        expect(response).to redirect_to(Network.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved network as @network" do
        post :create, {:network => invalid_attributes}, valid_session
        expect(assigns(:network)).to be_a_new(Network)
      end

      it "re-renders the 'new' template" do
        post :create, {:network => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        { description: "brabbelfasel" }
      }

      it "updates the requested network" do
        network = Network.create! valid_attributes
        put :update, {:id => network.to_param, :network => new_attributes}, valid_session
        network.reload
        expect(network.description).to be == "brabbelfasel"
      end

      it "assigns the requested network as @network" do
        network = Network.create! valid_attributes
        put :update, {:id => network.to_param, :network => valid_attributes}, valid_session
        expect(assigns(:network)).to eq(network)
      end

      it "redirects to the network" do
        network = Network.create! valid_attributes
        put :update, {:id => network.to_param, :network => valid_attributes}, valid_session
        expect(response).to redirect_to(network)
      end
    end

    describe "with invalid params" do
      it "assigns the network as @network" do
        network = Network.create! valid_attributes
        put :update, {:id => network.to_param, :network => invalid_attributes}, valid_session
        expect(assigns(:network)).to eq(network)
      end

      it "re-renders the 'edit' template" do
        network = Network.create! valid_attributes
        put :update, {:id => network.to_param, :network => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested network" do
      network = Network.create! valid_attributes
      expect {
        delete :destroy, {:id => network.to_param}, valid_session
      }.to change(Network, :count).by(-1)
    end

    it "redirects to the networks list" do
      network = Network.create! valid_attributes
      delete :destroy, {:id => network.to_param}, valid_session
      expect(response).to redirect_to(networks_url)
    end
  end

end
