require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OrgUnitsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # OrgUnit. As you add validations to OrgUnit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrgUnitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all org_units as @org_units" do
      org_unit = OrgUnit.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:org_units)).to eq([org_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested org_unit as @org_unit" do
      org_unit = OrgUnit.create! valid_attributes
      get :show, {:id => org_unit.to_param}, valid_session
      expect(assigns(:org_unit)).to eq(org_unit)
    end
  end

  describe "GET new" do
    it "assigns a new org_unit as @org_unit" do
      get :new, {}, valid_session
      expect(assigns(:org_unit)).to be_a_new(OrgUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested org_unit as @org_unit" do
      org_unit = OrgUnit.create! valid_attributes
      get :edit, {:id => org_unit.to_param}, valid_session
      expect(assigns(:org_unit)).to eq(org_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrgUnit" do
        expect {
          post :create, {:org_unit => valid_attributes}, valid_session
        }.to change(OrgUnit, :count).by(1)
      end

      it "assigns a newly created org_unit as @org_unit" do
        post :create, {:org_unit => valid_attributes}, valid_session
        expect(assigns(:org_unit)).to be_a(OrgUnit)
        expect(assigns(:org_unit)).to be_persisted
      end

      it "redirects to the created org_unit" do
        post :create, {:org_unit => valid_attributes}, valid_session
        expect(response).to redirect_to(OrgUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved org_unit as @org_unit" do
        post :create, {:org_unit => invalid_attributes}, valid_session
        expect(assigns(:org_unit)).to be_a_new(OrgUnit)
      end

      it "re-renders the 'new' template" do
        post :create, {:org_unit => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested org_unit" do
        org_unit = OrgUnit.create! valid_attributes
        put :update, {:id => org_unit.to_param, :org_unit => new_attributes}, valid_session
        org_unit.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested org_unit as @org_unit" do
        org_unit = OrgUnit.create! valid_attributes
        put :update, {:id => org_unit.to_param, :org_unit => valid_attributes}, valid_session
        expect(assigns(:org_unit)).to eq(org_unit)
      end

      it "redirects to the org_unit" do
        org_unit = OrgUnit.create! valid_attributes
        put :update, {:id => org_unit.to_param, :org_unit => valid_attributes}, valid_session
        expect(response).to redirect_to(org_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the org_unit as @org_unit" do
        org_unit = OrgUnit.create! valid_attributes
        put :update, {:id => org_unit.to_param, :org_unit => invalid_attributes}, valid_session
        expect(assigns(:org_unit)).to eq(org_unit)
      end

      it "re-renders the 'edit' template" do
        org_unit = OrgUnit.create! valid_attributes
        put :update, {:id => org_unit.to_param, :org_unit => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested org_unit" do
      org_unit = OrgUnit.create! valid_attributes
      expect {
        delete :destroy, {:id => org_unit.to_param}, valid_session
      }.to change(OrgUnit, :count).by(-1)
    end

    it "redirects to the org_units list" do
      org_unit = OrgUnit.create! valid_attributes
      delete :destroy, {:id => org_unit.to_param}, valid_session
      expect(response).to redirect_to(org_units_url)
    end
  end

end
